=== Jotaela/UF1NF3.3-Activitat3-/matricula.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="matricula">
        <xs:complexType>
            <xs:sequence>
              	<xs:element name="casa" type="xs:string"/>
                <xs:element ref="alumnes"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="alumnes">
        <xs:complexType>
            <xs:sequence>
              	<xs:element ref="alumne" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="alumne">
        <xs:complexType>
            <xs:sequence>
              	<xs:element name="nom" type="xs:string"/>
                <xs:element name="any" type="xs:integer"/>
                <xs:element ref="assignatures"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="assignatures">
        <xs:complexType>
            <xs:sequence>
              	<xs:element name="assignatura" type="xs:string" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Jotaela/UF1NF3.3-Activitat3-/matricula.xml
<?xml version="1.0" encoding="utf-8"?>
<matricula xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation='matricula.xsd'>
  <casa>Gryffindor</casa>
  <alumnes>
    <alumne>
      <nom>Hermione Granger</nom>
      <any>2013</any>
      <assignatures>
        <assignatura>Defensa contra las artes oscuras</assignatura>
        <assignatura>Pociones</assignatura>
      </assignatures>
    </alumne>
    <alumne>
      <nom>Ronald Weasley</nom>
      <any>2013</any>
      <assignatures>
        <assignatura>Pociones</assignatura>
      </assignatures>
    </alumne>
    <alumne>
      <nom>Harry Potter</nom>
      <any>2013</any>
      <assignatures>
        <assignatura>Pociones</assignatura>
        <assignatura>Herbologia</assignatura>
      </assignatures>
    </alumne>
    <alumne>
      <nom>Neville Longbottom</nom>
      <any>2013</any>
      <assignatures>
        <assignatura>Defensa contra las artes oscuras</assignatura>
      </assignatures>
    </alumne>
    <alumne>
      <nom>Ginny Weasley</nom>
      <any>2014</any>
      <assignatures>
        <assignatura>Defensa contra las artes oscuras</assignatura>
        <assignatura>Pociones</assignatura>
      </assignatures>
    </alumne>
    <alumne>
      <nom>Lee Jordan</nom>
      <any>2011</any>
      <assignatures>
        <assignatura>Defensa contra las artes oscuras</assignatura>
        <assignatura>Pociones</assignatura>
      </assignatures>
    </alumne>
    <alumne>
      <nom>Oliver Wood</nom>
      <any>2011</any>
      <assignatures>
        <assignatura>Pociones</assignatura>
      </assignatures>
    </alumne>
    <alumne>
      <nom>Colin Creevey</nom>
      <any>2014</any>
      <assignatures>
        <assignatura>Defensa contra las artes oscuras</assignatura>
        <assignatura>Pociones</assignatura>
        <assignatura>Herbologia</assignatura>
      </assignatures>
    </alumne>
  </alumnes>
</matricula>
